### ISSUE TITLE
Option for text to fade in as a block.

### ISSUE THREAD

**Issue by Mottelz** [TeamViral/ViralCurse#90]
I would like text to fade in as a block instead of just one letter at a time.

**Additional context**
I imagine it'll be another option in JSON called something like 
```JSON
"AnimateBy" : "Letter" || "Block" || "Word" || "sentence". 
```
The last two aren't that big a deal. it's the first two that matter more. Also might be nice to decide between fade and appear.

**Comment by Mottelz** [comment]
This is a robust request. The only real goal for now is to just have it fade in a block or appear letter by letter. (Fade should be silent.)

**Comment by StupidChris** [comment]
Yeah, I'm really not sure about the by word or sentence one, that seems like it makes little sense, but I know how to add block.

Instead, you would do this:
```json
"Speed": Infinity
```

It'd be treated as a special case in code and just be immediately shown rather than over time. No sound, just some fade if any is specified.

**Comment by Mottelz** [comment]
Can't I close this?

**Comment by StupidChris** [comment]
Well I can
